### ISSUE TITLE
more powerful source

### ISSUE THREAD

**Issue by cooler-SAI** [Joslyn-Maddie/MaddieCore-MOP#7]
Hey,man! I see you have done a lot of work here! I have more improoved source here https://github.com/cooler-SAI/JadeCore548-patched

- many scripts added
- many fixes too

I can add you with admin rights in repo, do what you want
so, what do you say?

**Comment by Joslyn-Maddie** [comment]
Sounds fun, Looking though the source right now and I see some great improvements.

**Comment by cooler-SAI** [comment]
@Joslyn-Maddie , added you to Repo, apply response and enjoy
